import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import Navbar from "./components/Navbar";
import Footer from "./components/Footer";
import "./globals.css";
import { Montserrat } from "next/font/google";
import Loading from "./Loading";
import { Suspense } from "react";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

const montserrat = Montserrat({
  weight: ["400"],
  style: ["normal"],
  subsets: ["latin"],
  display: "swap",
  variable: "--font-montserrat",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body
        className={`${montserrat.variable} antialiased min-h-screen flex flex-col
        bg-[linear-gradient(352.27deg,#171717_10%,#9C356D_12%,#F9784C_14%,#FCD68B_16%,#FFFAEF_18%,#FFFAEF_84%,#FCD68B_86%,#F9784C_87%,#9C356D_88%,#171717_90%)]
        text-white`}
      >
        <Navbar />

        <Suspense fallback={<Loading />}>
          <main className="flex-grow">
            {children}
          </main>
        </Suspense>

        <Footer />
      </body>
    </html>
  );
}
